server:
  port: 0

spring:
  application:
    name: server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

management:  endpoints:
    web:
      exposure:
        include: info